### ISSUE TITLE
Queries with SUM() in it doesnt seem to work

### ISSUE THREAD

**Issue by Fjorden** [vertica/vertica-prometheus-exporter#23]
I have multiple metrics, and all of them work except the ones that have the sum() in them, even the official one from the examples does not seem to work for me:
```
collector_name: sum_test
# min_interval: 0s
metrics:
  - metric_name: vertica_total_database_rows
    type: gauge
    help: "Total Rows in Database from projection_storage table."
    values: [ttlrows]
    query: |
      select /*+ LABEL(exporter_vertica_total_projection_rows) */ sum(row_count) as ttlrows 
      from projection_storage;
```
when queried directly returns:
```
default=> select /*+ LABEL(exporter_vertica_total_projection_rows) */ sum(row_count) as ttlrows
default->       from projection_storage;
 ttlrows
---------
   25080
(1 row)
```
but the exporter throws error:
`No metrics gathered, [from Gatherer #1] [collector="sum_test", query="vertica_total_database_rows"] scanning of query result failed: sql: Scan error on column index 0, name "ttlrows": converting NULL to float64 is unsupported`
